// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numOfLoops = Integer.parseInt(args[0]);
		int countInFirstHalf = 0;
		int  countInSecondHalf = 0;
		for (int i = 0; i < numOfLoops; i++) {
		    double randNum = Math.random();
			if (randNum <= 0.5) {
			    countInFirstHalf++;
			} 
			else {
			    countInSecondHalf++;
			}
		}
		System.out.println("> 0.5: " + countInFirstHalf + " times");
		System.out.println("<=0.5: " + countInSecondHalf + " times");
		if (countInSecondHalf != 0)	{
		System.out.println("Ratio " + ((double) countInFirstHalf / countInSecondHalf));
		}
	}
}
